#:schema https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/rust-toolchain.json
# @help: https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

[toolchain]
channel = "nightly"
components = ["rustc-codegen-cranelift-preview"]
