_default:
    @just --list

deploy:
    docker stack deploy --compose-file "./docker/compose.yml" --detach=false "marine"

rm:
    docker stack rm --detach=false "marine"

rmv:
    docker volume rm --force "marine_mariadb_data"
    docker volume rm --force "marine_mssql_data"
    docker volume rm --force "marine_psql_data"
