#:schema https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/cargo.json
# @help: https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]

[dependencies]
fern = "0.7.0"
humantime = "2.1.0"
log.workspace = true
polyphase = { path = "../../lib/polyphase/" }

[dev-dependencies]

[features]

[package]
authors.workspace = true
description.workspace = true
edition.workspace = true
license-file.workspace = true
name = "sort"
readme.workspace = true
repository.workspace = true
version = "0.1.0"
