# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
# @help: https://docs.docker.com/compose/compose-file

x-healthcheck: &healthcheck
  interval: "10s"
  retries: 3
  start_period: "10s"
  timeout: "5s"

secrets:
  mariadb_pswd:
    external: true
  mssql_pswd:
    external: true
  psql_pswd:
    external: true

services:
  mariadb:
    environment:
      MARIADB_ROOT_PASSWORD_FILE: "/run/secrets/mariadb_pswd"
    healthcheck:
      <<: *healthcheck
      test:
        - "CMD"
        - "healthcheck.sh"
        - "--connect"
        - "--innodb_initialized"
    # @see: https://mariadb.org/mariadb/all-releases
    image: "docker.io/library/mariadb:11.6.2"
    ports:
      - published: 3306
        target: 3306
    secrets:
      - "mariadb_pswd"
    user: "mysql"
    volumes:
      - source: "mariadb_data"
        target: "/var/lib/mysql/"
        type: "volume"

  mssql:
    environment:
      ACCEPT_EULA: "true"
      MSSQL_SA_PASSWORD_FILE: "/run/secrets/mssql_pswd"
    healthcheck:
      <<: *healthcheck
      test:
        - "CMD-SHELL"
        - '/opt/mssql-tools18/bin/sqlcmd -C -P "$$(cat /run/secrets/mssql_pswd)" -U "sa" -Q "select 1;"'
    # @see: https://learn.microsoft.com/troubleshoot/sql/releases/download-and-install-latest-updates
    image: "mcr.microsoft.com/mssql/server:2022-CU16-ubuntu-22.04"
    ports:
      - published: 1433
        target: 1433
    secrets:
      - "mssql_pswd"
    user: "mssql"
    volumes:
      - source: "mssql_data"
        target: "/var/opt/mssql/"
        type: "volume"

  psql:
    environment:
      POSTGRES_PASSWORD_FILE: "/run/secrets/psql_pswd"
    healthcheck:
      <<: *healthcheck
      test:
        - "CMD"
        - "pg_isready"
    # @see: https://www.postgresql.org/docs/release
    image: "docker.io/library/postgres:17.2"
    ports:
      - published: 5432
        target: 5432
    secrets:
      - "psql_pswd"
    user: "postgres"
    volumes:
      - source: "psql_data"
        target: "/var/lib/postgresql/data/"
        type: "volume"

volumes:
  mariadb_data:
  mssql_data:
  psql_data:
