# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
# @help: https://docs.docker.com/compose/compose-file

secrets:
  mariadb_pswd:
    external: true
  mssql_pswd:
    external: true
  psql_pswd:
    external: true

services:
  mariadb:
    environment:
      MARIADB_ROOT_PASSWORD_FILE: "/run/secrets/mariadb_pswd"
    # @see: https://mariadb.org/mariadb/all-releases
    image: "docker.io/library/mariadb:11.6.2"
    secrets:
      - "mariadb_pswd"

  mssql:
    environment:
      ACCEPT_EULA: "true"
      MSSQL_SA_PASSWORD_FILE: "/run/secrets/mssql_pswd"
    # @see: https://learn.microsoft.com/troubleshoot/sql/releases/download-and-install-latest-updates
    image: "mcr.microsoft.com/mssql/server:2022-CU16-ubuntu-22.04"
    secrets:
      - "mssql_pswd"

  psql:
    environment:
      POSTGRES_PASSWORD_FILE: "/run/secrets/psql_pswd"
    # @see: https://www.postgresql.org/docs/release
    image: "docker.io/library/postgres:17.2"
    secrets:
      - "psql_pswd"
