# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
# @help: https://docs.docker.com/compose/compose-file

name: s3_db-p02

services:
  db:
    env_file:
      - ../.env
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - pg_isready
      timeout: 5s
    # image: docker.io/library/postgres:17.1
    image: registry.gitlab.com/dalibo/postgresql_anonymizer@sha256:85f6a5918bf541cfd1cd43c802e148960611bfc4e8e3e55a9baff5bc523756a2 # 2.0.0-rc.1
    ports:
      - published: 5432
        target: 5432
    pull_policy: if_not_present
    restart: unless-stopped
    volumes:
      - source: ../sql/
        target: /docker-entrypoint-initdb.d/
        type: bind
      - source: db_data
        target: /var/lib/postgresql/data/
        type: volume

volumes:
  db_data:
